### ISSUE TITLE
Create tags with go-netbox and netbox 2.9

### ISSUE THREAD

**Issue by smutel** [netbox-community/go-netbox#101]
Hello,

Is-it possible to create a tag using go-netbox in netbox 2.9 ?
Since netbox 2.9, tags are implemented differently in go-netbox (NestedTags).
I didn't found any writable_tag.go ...

Thanks.

**Comment by erikkn** [comment]
Hey Smutel! Checkout this issue right here: https://github.com/netbox-community/go-netbox/issues/99

**Comment by smutel** [comment]
Hello Erik,

In this example, it's explained how to associate an existing tag to a resource.
What about creating the tag from scratch ?

Thanks.

**Comment by erikkn** [comment]
What do you mean by creating a tag from scratch? When you say from scratch I start thinking about the `extras` package.

**Comment by smutel** [comment]
I mean like in the web interface Organization => Tags.
Yes you are right it's the extras package then tags to manage tags through the API.
But in the go-netbox library do we have something to add/remove tags ?

**Comment by erikkn** [comment]
Right, so when you say 'create tags from scratch' you mean how one would create tags through the  'Organization -> Tags' tab.

I do this by using the `extras` package, specifically, the `ExtrasTagsCreate` method -> https://godoc.org/github.com/netbox-community/go-netbox/netbox/client/extras#Client.ExtrasTagsCreate

**Comment by smutel** [comment]
Thanks for this info.
