### ISSUE TITLE
Netbox Secrets Session Key

### ISSUE THREAD

**Issue by sc0ttes** [netbox-community/go-netbox#114]
Does go-netbox support "X-Session-Key" for returning plaintext secrets [as so](https://netbox.readthedocs.io/en/stable/rest-api/working-with-secrets/)? From what I can gather it appears I would need to implement a custom client to make the initial POST with the user's private key, returning the session key and would then need to create another custom client that calls the Secrets endpoints with both the API Key and the Session Key correct?

Would love any thoughts on any better ways to do this. Was originally thinking of adding the optional private key path during client init, then using the above to get the session key, and subsequently using APIKeyAuth to pass both the API Key and Session Key on all requests.

**Comment by v0ctor** [comment]
Closing, as secrets were removed from Netbox.
