### ISSUE TITLE
Unable to remove date added in aggregate object

### ISSUE THREAD

**Issue by smutel** [netbox-community/go-netbox#115]
Hello,

I am not able to remove `date added` in aggregate object.
It seems that using the empty value for `date added` (https://stackoverflow.com/questions/23051973/what-is-the-zero-value-for-time-time-in-go) does not remove the date in the object.
`nil` value does not do the job also.

Any tips or workaround to achieve this ?

**Comment by v0ctor** [comment]
Closing in favor of #107.
