### ISSUE TITLE
client for netbox 2.10

### ISSUE THREAD

**Issue by kplimack** [netbox-community/go-netbox#117]
When will a client for 2.10 be released ?

**Comment by smutel** [comment]
First beta for netbox 2.11 https://github.com/netbox-community/netbox/releases/tag/v2.11-beta1 ...

This project was moved to netbox-community due to lack of reactivity from digitalocean.
But it seems to be the same here ... :cry:

**Comment by awlx** [comment]
Problem is ... I think most of the maintainers don't use the project anymore themselves so we depend on PRs :(.

**Comment by smutel** [comment]
I understand that maintainers cannot maintain alone this project, it's really time consuming, most of us have a job and maintaining github repo is not part of our job ...

Issues are coming when maintainers does not have time to review PRs and commit them.  
And we can see a lot of projects in github in this situation.

**Comment by awlx** [comment]
Wasn't meant as offence just a fact :). And yeah, it's a sad situation I would like to really help more. But as I am not using go-netbox anymore it's quite hard to keep it up to date.

**Comment by pezhore** [comment]
Perhaps a stupid question, but are the maintainers open to adding more volunteers to the repo?

**Comment by smutel** [comment]
I created my own lib: https://github.com/smutel/go-netbox

**Comment by tagur87** [comment]
FYI, the client has been updated to support v2.11.11

**Comment by v0ctor** [comment]
Closing, because Netbox 2.10 is almost two years old and there is [a release for 2.11](https://github.com/netbox-community/go-netbox/releases/tag/netbox_v2.11).

Anyway, if someone still needs a release for 2.10, feel free to [generate it](https://github.com/netbox-community/go-netbox#development) and open a PR.
