### ISSUE TITLE
Unable to write json string to device's local_context_data

### ISSUE THREAD

**Issue by stefanhipfel** [netbox-community/go-netbox#118]
Hi,

I currently want to write some struct data to a device's local_context_data. However since this parameter needs to be a *string ([local_context_data](https://github.com/netbox-community/go-netbox/blob/master/netbox/models/writable_device_with_config_context.go#L88)), I need to json.Marshal my go struct to a string.
When using the go [openapi runtime](https://github.com/go-openapi/runtime/blob/master/json.go#L36) as the client.Transport, it will however json.Encode the request body again (due to the mediaType being "application/json") which just escapes my json string (e.g. "{/"foo/":/"bar/"}). The Netbox API will then respond with a 400 error:
`PUT /dcim/devices/{id}/][400] dcim_devices_update default  map[local_context_data:[JSON data must be in object form. Example: {“foo”: 123}]`

The issue could be solved if the local_context_data parameter is an interface{}, so the runtime can correctly handle the json encoding! Was there a specific reason the have a string instead?
Thanks

**Comment by v0ctor** [comment]
Closing, as now `local_context_data` is defined as an object in the OpenAPI specification.
