### ISSUE TITLE
GET site list details with custom field  

### ISSUE THREAD

**Issue by ram-memx** [netbox-community/go-netbox#125]
Hi All. I am pretty new to use golang client for netbox. I am trying to get the site list from Netbox and I would like to filter it using a custom field. Can you please let me know how to pass that custom field to "**dcim.NewDcimSitesListParams()**" function? Are custom fields supported using golang client? If not please let me know the best way to achieve this functionality. Thanks

**Comment by dechristopher** [comment]
Also looking to do such things. If there's no info I might just open a PR soon implementing it.

**Comment by dechristopher** [comment]
Looks like the NetBox REST API doesn't support providing custom field parameters. We're out of luck until that's added to the API. For now, we'll need to do client-side filtering to weed out devices that don't have the field values we're looking for.

**Comment by dechristopher** [comment]
```go
// make a struct for your custom fields
type CustomFields struct {
	Custom bool `json:"custom_field_name"`
}

// grab all devices
params := dcim.NewDcimDevicesListParams()
resp, err := client.Dcim.DcimDevicesList(params, nil)
if err != nil {
	return nil, err
}

filteredDevices := make([]*models.DeviceWithConfigContext, 0)

// filter down custom fields
for _, device := range resp.Payload.Results {
	customFields, ok := device.CustomFields.(CustomFields)
	if !ok {
		// issues
	}

	if customFields.Custom {
		filteredDevices = append(filteredDevices, device)
	}
}

// etc, ymmv
```

**Comment by v0ctor** [comment]
Closing, as it is a limitation of the Netbox API.

**Comment by tgoff** [comment]
It appears this is supported now in the netbox REST API: https://demo.netbox.dev/static/docs/rest-api/filtering/#filtering-by-custom-field
