### ISSUE TITLE
Package incompatible with NetBox v3.2.0

### ISSUE THREAD

**Issue by nleiva** [netbox-community/go-netbox#127]
NetBox 3.2 introduced breaking changes that make this package incompatible: https://github.com/netbox-community/netbox/releases/tag/v3.2.0. This is because of a change in the created timestamp of the API.

_The created field of all change-logged models now conveys a full datetime object, rather than only a date. (Previous date-only values will receive a timestamp of 00:00.) While this change is largely unconcerning, strictly-typed API consumers may need to be updated._

I run into this issue when using the Terraform NetBox provider: https://github.com/e-breuninger/terraform-provider-netbox/issues/145.

I believe this is because [go-netbox](https://github.com/netbox-community/go-netbox) depends on [strfmt](https://github.com/go-openapi/strfmt) v0.20.2, that defines `RFC3339FullDate`:

```go
const (
	// RFC3339FullDate represents a full-date as specified by RFC3339
	// See: http://goo.gl/xXOvVd
	RFC3339FullDate = "2006-01-02"
)
```
https://github.com/go-openapi/strfmt/blob/v0.20.2/date.go#L39-L43

To parse instances of `"date"`.

```go
  case "date":
	  d, err := time.Parse(RFC3339FullDate, data.(string))
	  if err != nil {
		  return nil, err
	  }
```
https://github.com/go-openapi/strfmt/blob/v0.20.2/format.go#L105-L109

Which is what they use to parse the created responses. So it only expects a date.

```go
func (m *Platform) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}
```

I reproduced this error in the Go playground -> [https://go.dev/play/p/Kybi_Kguigf](https://go.dev/play/p/Kybi_Kguigf).

Thanks.

**Comment by wfyanmnm** [comment]
@nleiva I am not femilliar with go lang, is there a quick way to fix it on code level?

**Comment by v0ctor** [comment]
This issue has been fixed in [the latest release](https://github.com/netbox-community/go-netbox/releases/tag/netbox_v3.2). It may be closed. 🎉
