### ISSUE TITLE
time.ParseError in v3.2

### ISSUE THREAD

**Issue by mikeestrada** [netbox-community/go-netbox#142]
Potentially related to [127](https://github.com/netbox-community/go-netbox/issues/127)

When running Netbox version 3.2 (which equates to v0.0.0-20220627164555-1099c67af5a7) and invoking `GetDeviceByID()`, I receive the following error: 
`*time.ParseError(&time.ParseError{Layout:"2006-01-02 15:04:05", Value:"2021-05-29", LayoutElem:"15", ValueElem:"", Message:""})`.

I have downgraded several versions along with the `strfmt` package but all seem to yield the same or different errors. 
Thanks!

cc: @v0ctor

**Comment by v0ctor** [comment]
Hi!

I don't understand what do you mean by invoking `GetDeviceByID()`, since there's no such function. To retrieve a device by its ID, you need to invoke `DcimDevicesRead()`.

I've tried the snippet below with the version you are using and it worked fine. Please, replace `<host>`, `<token>` and `<deviceID>` by yours.

```
package main

import (
	"fmt"

	runtimeclient "github.com/go-openapi/runtime/client"
	"github.com/netbox-community/go-netbox/netbox/client"
	"github.com/netbox-community/go-netbox/netbox/client/dcim"
)

func main() {
	t := runtimeclient.New("<host>", client.DefaultBasePath, []string{"https"})

	t.DefaultAuthentication = runtimeclient.APIKeyAuth(
		"Authorization",
		"header",
		fmt.Sprintf("Token %v", "<token>"),
	)

	nbx := client.New(t, nil)

	req := dcim.
		NewDcimDevicesReadParams().
		WithID(<deviceID>)

	dev, err := nbx.Dcim.DcimDevicesRead(req, nil)

	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v", dev)
}

```
