### ISSUE TITLE
add Devices and InventoryItems for v2 API

### ISSUE THREAD

**Issue by davcamer** [netbox-community/go-netbox#15]
I need this for a project I'm working on at the moment. I'll follow the code generation pattern introduced by @chrigl.

**Comment by d0m0reg00dthing** [comment]
I'm working on DCIM/Devices but I stuck at how to represent 'is_console_server' in **ListDeviceTypeOptions** type. In return json, **is_console_server** is True/False but in filter, this can be empty also. Any idea how to represent this in **ListDeviceTypeOptions**

**Comment by davcamer** [comment]
I think a `*bool` is appropriate here. If `nil` then don't include `is_console_server` as a parameter at all. If non-nil, then include it with the appropriate value.

**Comment by d0m0reg00dthing** [comment]
I have pushed to my github the first version of my **Device** implementation. Could you have sometime to check it and give me some suggestion on how to optimize that code. If the code is good enough, I will create a pull request soon.

Another thing I need help is about `ParentDevice`, I don't know how to add a device with a parent device to see what exactly it is in Netbox response JSON.

**Comment by davcamer** [comment]
`ParentDevice` is used when a "parent" device has "child" devices in device bays. There are a few steps to create one:

1. create a device type which is a parent
1. create a device type which is a child
1. create a device of the parent device type
1. add device bays to this device
1. create a device of the child device type (and assign to the same site as the parent)
1. on the parent's device detail page, use the + button in the device bay to add the child in to that bay
1. now the parent should appear in the child's API entry as the `parent_device`

Would be good to see the UnmarshalJSON test completed.

Make sure to follow all the steps in `CONTRIBUTING.md` for the PR. I ran through the `go fmt`... sequence a few times when I was polishing the inventory items code, because the later step would introduce something that an earlier step needed to check again.

Otherwise, the code is looking good to me.
