### ISSUE TITLE
Cannot set MarkUtilized to false when doing IpamPrefixesPartialUpdate

### ISSUE THREAD

**Issue by ArnoSen** [netbox-community/go-netbox#152]
The problem is caused by a combination of variable type and json tags in models.WritablePrefix:

```
       MarkUtilized bool `json:"mark_utilized,omitempty"`
```

The 'omitempty' triggers that the default value for bool which is false is omitted from the JSON.
I think the best solution is that MarkUtilized becomes a pointer variable. I do not know how this can be easily changes in the OpenAPI definition.

**Comment by v0ctor** [comment]
A new [alpha version](https://github.com/netbox-community/go-netbox/releases/tag/v3.7.1-alpha.0) has been released with a different software to generate the library, so hopefully this bug has been resolved.

Please feel free to test it and to provide feedback.
