### ISSUE TITLE
Netbox 3.5+ support

### ISSUE THREAD

**Issue by jqueuniet** [netbox-community/go-netbox#155]
I realise this is far from trivial given the upstream switch to OpenAPI 3 which is not supported by go-swagger, but is there currently any plan for Netbox 3.5+ support in this project? And is there any need for help to move forward on this issue?

**Comment by v0ctor** [comment]
I created [a discussion](https://github.com/netbox-community/go-netbox/discussions/156) to address the migration to a library compatible with OpenAPI 3.

I also created [an experimental PR](https://github.com/netbox-community/go-netbox/pull/157) to test _[openapi-generator](https://github.com/OpenAPITools/openapi-generator)_, as it seems the most viable option.

Please feel free to participate! 🤩

**Comment by davidovich** [comment]
May I also suggest https://github.com/deepmap/oapi-codegen which is written in go, so may lower the impedance mismatch. It generates idiomatic go and is compatible with OpenAPI 3.

**Comment by tjdavis3** [comment]
Another suggesting is https://github.com/ogen-go/ogen.  Similar to oapi-codegen and also written in go.

**Comment by v0ctor** [comment]
After investigating these options and others that I finally discarded, I made another PR (#161) using _[oapi-codegen](https://github.com/deepmap/oapi-codegen)_ as an alternative.

I am going to try it out, but at the moment I like this alternative better because it seems simpler and more idiomatic.

**Comment by zyxep** [comment]
any updates on this one?
the new OAPI specs is kinda blocking me from upgrading my netbox instance :(
