### ISSUE TITLE
Netbox 3.6 field defintions don't match

### ISSUE THREAD

**Issue by gboor** [netbox-community/go-netbox#159]
I'm on Netbox 3.6 and found that the definition of `WritableDeviceWithConfigContext` is incorrect. In the API definition it asks for a `role` field with an integer ID for the role, but in this generated client, the field is called `device_role`, which no longer seems to exist. This means I cannot create a device with this library.

Is there any way to resolve this without locally overriding the model?

**Comment by davidovich** [comment]
see #155.
