### ISSUE TITLE
CustomFieldType* missing support for 'datetime' fields

### ISSUE THREAD

**Issue by nneul** [netbox-community/go-netbox#163]
In several places including the type label and the CustomFieldTypeLabel and CustomFieldTypeValue sections.

**Comment by v0ctor** [comment]
A new [alpha version](https://github.com/netbox-community/go-netbox/releases/tag/v3.7.1-alpha.0) has been released with a different software to generate the library, so hopefully this bug has been resolved.

Please feel free to test it and to provide feedback.
