### ISSUE TITLE
Role field is missing in struct WritableDeviceWithConfigContext

### ISSUE THREAD

**Issue by rogerscuall** [netbox-community/go-netbox#164]
Trying to create any device the with the version `v3.4.5` should fail, because the struct`WritableDeviceWithConfigContext` is missing the field `Role`. Not sure where/when this broke, but on the version `3.6.3` of `openapi.yml` I can see the WritableDeviceWithConfigContextRequest has a field/property named `Role` instead of `DeviceRole`. To fix this I'm just rebuilding and seems to work for me.

**Comment by v0ctor** [comment]
A new [alpha version](https://github.com/netbox-community/go-netbox/releases/tag/v3.7.1-alpha.0) has been released with a different software to generate the library, so hopefully this bug has been resolved.

Please feel free to test it and to provide feedback.

**Comment by rogerscuall** [comment]
It did indeed. That is how I'm running now. I only found 2 minor issues with your relase. I have been using it with it for the last week. Thanks for letting me know I will update to the latest version soon. Thanks again.
