### ISSUE TITLE
Readme is incorrect to install netbox golang package

### ISSUE THREAD

**Issue by softengineer** [netbox-community/go-netbox#169]
Followed readme instruction, I tried to install golang package by command : 

go get github.com/netbox-community/go-netbox/v3@v3.7.1-0

And got error:
go: github.com/netbox-community/go-netbox/v3@v3.7.1-0: invalid version: unknown revision v3.7.1-0

Also if just type:
go get github.com/netbox-community/go-netbox/v3

The result in go.mod is not latest version of v3 (assume it should be  v3.7.1-0)

It  works for using correct tag by command:
go get github.com/netbox-community/go-netbox/v3@v3.7.1-alpha.0

**Comment by v0ctor** [comment]
Fixed. Thanks!

**Comment by v0ctor** [comment]
Fixed. Thanks!
