### ISSUE TITLE
IPAM management

### ISSUE THREAD

**Issue by zlesnr** [netbox-community/go-netbox#25]
There doesn't currently look to be any related code for IPAM management.  Is this correct?  If so, is this actively being worked on?  If not, what did I miss?

**Comment by mdlayher** [comment]
Yep, it hasn't been added to the 2.0 client yet. PRs welcome.

**Comment by zlesnr** [comment]
Sure.  @mdlayher Can you explain what's going on with the NewPage options calls?  What are the options intended to do?

It looks like I can probably follow some of the existing code, but there are several URLs under the `/ipam/` controller that will need to be built out.

**Comment by mdlayher** [comment]
Been a bit since I've looked into it, but perhaps @chrigl can shed some light?  Otherwise I can try to dive back in tomorrow.

**Comment by chrigl** [comment]
All List funcs return are supposed to return a Page. This Page will issue the request in its Next func. The options passed into the List func, and down to NewPage hold the query data for the List-Request.

For example. List all Devices of Tenant 1
```
pager := client.DCIM.Devices.List(&netbox. ListDeviceOptions{TenantID: 1})

for page.Next() {
        res, err := client.DCIM.Devices.Extract(page)
        ...
}
```

The Page does also take care about limit and offset query params for paging the api results.

**Comment by zlesnr** [comment]
Thanks for the info.  Its not looking like I have a spare afternoon this week, so I'll try to come back to this.  I'm not currently using netbox but would like to, but to populate the database I'd like some kind of API support, so this would need fleshed out first, or come up with a hack to load the data so we can use netbox.
