### ISSUE TITLE
Several fields have number as type in swagger.json

### ISSUE THREAD

**Issue by hensoko** [netbox-community/go-netbox#33]
Hi,

I recently noticed that several properties in the swagger.json have the type number where I expected integer. This is especially the case for several ID properties like device_id in operation dcim_interfaces_list.

Is there a special reason for this?

I also noticed that several _id fields have string as type when being used as query param.

**Comment by redsux** [comment]
Hi,

It also concern other types, i found an issue with the **Interface** struct.

`netbox/models/interface.go` field `IsConnected` is define as a **string** but we got a **bool** from the JSON.

So go-netbox failed to unmarshal it correctly : `cannot unmarshal bool into Go struct field Interface.is_connected of type string`.
