### ISSUE TITLE
The client is not compliant with netbox latest API

### ISSUE THREAD

**Issue by fcgravalos** [netbox-community/go-netbox#40]
Just trying to create a simple VLAN throws json unmarshalling issues:

```
json: cannot unmarshal object into Go struct field WritableVLAN.status of type int64
```

Just curl against the API is pretty clear that the `status` field should be either struct or `map[string]inerface{}`

```
 "status": {
    "value": 1,
    "label": "Active"
  },
```

This is a major bug guys...

**Comment by awlx** [comment]
Fixed via #47
