### ISSUE TITLE
set meaning descriptions in swagger.json

### ISSUE THREAD

**Issue by kobayashi** [netbox-community/go-netbox#50]
godoc shows meaningless descriptions for some client’s methods
For example, ExtrasConfigContextsList is described as `Call to super to allow for caching`
https://godoc.org/github.com/netbox-community/go-netbox/netbox/client/extras

swagger.json is generated automatically from netbox itself though, for the current version netbox v2.6 at least, it does not provide meaning descriptions.

**Comment by awlx** [comment]
Is it worth the effort? Or should it be fixed in the generated swagger.json?

**Comment by kobayashi** [comment]
Ah yeah, swagger.json shows me over 100 lines. Is it better to delete the comment or leave as it is?

```
$ grep "Call to super to allow for caching" swager.json |wc -l
116
```

**Comment by kobayashi** [comment]
Close this issue because this may not worth.
