### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by smutel** [netbox-community/go-netbox#57]
Hello,

Could you please create a new tag for this library ?
I am using `Gopkg.toml` and `dep` command and it seems that I can only lock version with tags, not master.

Thanks.

**Comment by kobayashi** [comment]
What kind of tags you need?

**Comment by smutel** [comment]
I need a git tag on this repository ...

In my `Gopkg.toml`, I have this:
```ini
[[constraint]]                                                                  
  name = "github.com/netbox-community/go-netbox"                                
  version = "netbox_v2.4"
```

But the netbox_v2.4 tag is not good for me. I need a more recent tag to use in my code.

**Comment by kobayashi** [comment]
I just have set tag [netbox_v2.6](https://github.com/netbox-community/go-netbox/tree/netbox_v2.6) from the current master.

**Comment by smutel** [comment]
Hello,

Thank you for the tag.
Previously I used this piece of code but it seems that the function NewNetboxWithAPIKey does not exist anymore:

```go
import (                
  netboxapi "github.com/netbox-community/go-netbox/netbox"                      
)

func configureProvider(d *schema.ResourceData) (interface{}, error) {           
  url := d.Get("url").(string)                                                  
  token := d.Get("token").(string)                                              
                                                                                
  return netboxapi.NewNetboxWithAPIKey(url, token), nil                         
}
```

Could you please help me to convert this code with the netbox_2.6 tag ?

**Comment by kobayashi** [comment]
Added new tag netbox_2.7 which include netbox package. Plz check it. Thanks!

**Comment by smutel** [comment]
Is this tag compatible with Netbox 2.6 ?
