### ISSUE TITLE
Swagger out of date with v2.8

### ISSUE THREAD

**Issue by stefanmcshane** [netbox-community/go-netbox#79]
Swagger json is on 2.7, there are a lot of new changes in Netbox v2.8 with regards to the OAS spec.

Can we get a new build of the swagger.json added to this repo?

**Comment by kobayashi** [comment]
Opened PR https://github.com/netbox-community/go-netbox/pull/81 for this.

**Comment by smutel** [comment]
The swagger is now up to date with v2.8 but out of date with v2.9.
When the update is planned ? Is-it possible to manage #68 before ?
