### ISSUE TITLE
Upstream patches of forked go-netbox client

### ISSUE THREAD

**Issue by hensoko** [netbox-community/go-netbox#93]
Hey there,

we're using netbox with go for quite some time now but started working on a fork of go-netbox as the swagger.json was often out of date. I'm currently preparing simple patches that can be applied hopefully against new versions of swagger.json to fix several (type of *_id fields / number fields) and wonder how I can help upstream.

You can find my changes in [feature/modernize](https://github.com/hosting-de-labs/go-netbox/tree/feature/modernize).

Regards

**Comment by awlx** [comment]
I just merged https://github.com/netbox-community/go-netbox/pull/92 so we have master working with netbox 2.9

**Comment by hensoko** [comment]
As far as I can see there are still several fields that can not be defined right. 

For example: /virtualization/cluster-types or /virtualization/clusters
The id field of the list operation is defined as string instead of integers. I have a lot of examples of this kind that I have fixed, eg for virtualization see [here](https://github.com/hosting-de-labs/go-netbox/commit/8a3ccb25f0a75466d5ea9114473504d4a2773071#diff-702be237a87f80c305c9755b62bc42f9)

**Comment by awlx** [comment]
Could you make a PR with the revlevant changes?

**Comment by hensoko** [comment]
Sure, gonna prepare somthing.

**Comment by v0ctor** [comment]
Closing, because now there are two ways to fix issues in generated code:
- Changing the OpenAPI spec with pre-generation hooks (see [`scripts/pre-generation`](scripts/pre-generation)).
- If the above is not possible, changing the generated code with post-generation hooks (see [`scripts/post-generation`](scripts/post-generation)).
