### ISSUE TITLE
IPAM: IP Address lookup with multiple configured tags

### ISSUE THREAD

**Issue by erikkn** [netbox-community/go-netbox#95]
Hi folks,

Pretty new to the scene, but I was wondering how one looks-up an IP address / IP address based on the configured tags.
When I use the following snippet, it is working fine:

`     
     tags1 := "test"
 
     params := ipam.NewIpamIPAddressesListParams()
     params.SetTagn(&tags1)
 
     ipOk, err := c.IpamIPAddressesList(params, nil)
     if err != nil {
         log.Fatalf("[ERROR:] ", err)
     }
`

Question: How do I look up an IP address / IP addresses that have multiple tags configured?

Thank you :)

**Comment by v0ctor** [comment]
It seems that it is a Netbox API limitation or a problem with the OpenAPI specification.

If still relevant, please, refer to the [Netbox project](https://github.com/netbox-community/netbox/issues) to report this issue.
